// Generates graph analysis as Markdown and copies to clipboard via the host.

function generateAnalysisMarkdown(parsed, a, st) {
  var dn = function (id) { return parsed.displayNames[id] || id; };

  var md = '';
  md += '# Agent Graph Analysis\n\n';
  md += '_Generated by AgentLens · ' + new Date().toLocaleString() + '_\n\n';

  md += '## 1. Execution Summary\n\n';
  md += '| Metric | Value |\n|---|---|\n';
  md += '| Total Steps | ' + st.steps + ' |\n';
  md += '| LLM Calls | ' + st.llm + ' |\n';
  md += '| Function Calls | ' + st.fn + ' |\n';
  md += '| Transitions | ' + st.transition + ' |\n';
  md += '| Wall Time | ' + st.wall + 'ms |\n';
  md += '| Sub Agents | ' + a.n + ' |\n\n';

  md += '## 2. Graph Structure\n\n';
  md += '| Metric | Value |\n|---|---|\n';
  md += '| Vertices |V| | ' + a.n + ' |\n';
  md += '| Edges (multigraph) | ' + a.mMulti + ' |\n';
  md += '| Edges (simple) | ' + a.mUnique + ' |\n';
  md += '| Density | ' + a.density.toFixed(4) + ' |\n';
  md += '| Undirected Diameter | ' + a.diam + ' |\n';
  md += '| Weakly Connected Components | ' + a.wcc.length + ' |\n';
  md += '| Strongly Connected Components | ' + a.scc.count + ' |\n';
  md += '| Redundant Edges | ' + a.redundancy + ' |\n\n';

  md += '## 3. Interpretation\n\n';
  for (var pi = 0; pi < a.prose.length; pi++) {
    var line = a.prose[pi].replace(/<strong>/g, '**').replace(/<\/strong>/g, '**').replace(/<[^>]+>/g, '');
    md += '> ' + line + '\n>\n';
  }
  md += '\n';

  md += '## 4. Degree Analysis\n\n';
  md += '| Sub Agent | In-degree | Out-degree | Total |\n|---|---:|---:|---:|\n';
  for (var di = 0; di < parsed.topics.length; di++) {
    var t = parsed.topics[di];
    md += '| ' + dn(t) + ' | ' + a.indeg[t] + ' | ' + a.outdeg[t] + ' | ' + (a.indeg[t] + a.outdeg[t]) + ' |\n';
  }
  md += '\n';

  md += '## 5. Transition Edges\n\n';
  md += '| From | To | Count |\n|---|---|---:|\n';
  var sorted = [...parsed.transitionEdges].sort(function (x, y) { return y.count - x.count; });
  for (var ei = 0; ei < sorted.length; ei++) {
    var e = sorted[ei];
    md += '| ' + dn(e.from) + ' | ' + dn(e.to) + ' | ' + e.count + ' |\n';
  }
  md += '\n';

  md += '## 6. Self-Loops\n\n';
  if (a.selfLoops.length) {
    md += '| Sub Agent | Count |\n|---|---:|\n';
    for (var si = 0; si < a.selfLoops.length; si++) {
      md += '| ' + dn(a.selfLoops[si].from) + ' | ' + a.selfLoops[si].count + ' |\n';
    }
  } else {
    md += 'None\n';
  }
  md += '\n';

  md += '## 7. Weakly Connected Components\n\n';
  md += '| Component | Members | Size |\n|---|---|---:|\n';
  for (var wi = 0; wi < a.wcc.length; wi++) {
    md += '| Component ' + (wi + 1) + ' | ' + a.wcc[wi].map(dn).join(', ') + ' | ' + a.wcc[wi].length + ' |\n';
  }
  md += '\n';

  md += '## 8. Strongly Connected Components\n\n';
  var nontrivial = a.scc.groups.filter(function (g) { return g.length > 1; });
  if (nontrivial.length) {
    md += '| SCC | Members | Size |\n|---|---|---:|\n';
    for (var sci = 0; sci < nontrivial.length; sci++) {
      md += '| SCC ' + (sci + 1) + ' | ' + nontrivial[sci].map(dn).join(', ') + ' | ' + nontrivial[sci].length + ' |\n';
    }
  } else {
    md += 'None — the graph is acyclic (DAG)\n';
  }
  md += '\n';

  md += '## 9. Betweenness Centrality\n\n';
  if (a.maxBt) {
    md += '**Highest betweenness:** ' + dn(a.maxBt) + ' (' + a.maxBtVal.toFixed(4) + ')\n\n';
  }
  if (a.between) {
    md += '| Sub Agent | Betweenness |\n|---|---:|\n';
    var btList = parsed.topics.map(function (t) { return { t: t, b: a.between[t] }; }).sort(function (x, y) { return y.b - x.b; });
    for (var bi = 0; bi < btList.length; bi++) {
      md += '| ' + dn(btList[bi].t) + ' | ' + btList[bi].b.toFixed(4) + ' |\n';
    }
  } else {
    md += 'Skipped — graph exceeds 40 nodes\n';
  }
  md += '\n';

  md += '## 10. Graph Density\n\n';
  md += 'Density = ' + a.density.toFixed(4) + ' with ' + a.mUnique + ' unique edges out of ' + (a.n > 1 ? a.n * (a.n - 1) : 0) + ' possible.\n\n';

  md += '## 11. Undirected Diameter\n\n';
  md += 'Diameter = ' + a.diam;
  if (a.diam === 0) md += ' (single agent or fully disconnected)';
  else if (a.diam === 1) md += ' (all agents directly connected — star or complete topology)';
  else md += ' (up to ' + a.diam + ' hops between the most distant pair)';
  md += '\n';

  return md;
}

function copyAnalysisMarkdown() {
  var plan = currentData && currentData.plan;
  if (!plan || !vizParsed || !analysis) return;
  var st = computePlanExecutionStats(plan);
  var md = generateAnalysisMarkdown(vizParsed, analysis, st);
  postToHost('copyMarkdown', md);
}
